### ISSUE TITLE
Instead of an empty array, a multiselect control with no selected options submits ['']

### ISSUE THREAD

**Issue by charlieok** [cezary/jquery-html-json-forms#2]
If I have a 'select' element in a form with the 'multiple' attribute set, and none of the child options are selected, the resulting json value shows up as an array containing an empty string: ['']

I think the correct value in this situation should be an empty array: []

One possible fix:

Change line 142...

https://github.com/cezary/jquery-html-json-forms/blob/516cf16209eab346a4a0b1147b71fcdc34e477a7/lib/json-forms.js#L142

from

```javascript
      context = setValue(context, step, currentValue, entry.value, isFile);
```
to
```javascript
      if (!(step.type == "array" && entry.value == "")) {
        context = setValue(context, step, currentValue, entry.value, isFile);
      }
```

**Comment by cezary** [comment]
Forgot about the multiple attribute, thanks!
